
agent_name: lail_cl

agent:
  _target_: agents.lail_cl.LailClAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  log_std_bounds: [-5, 2]
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  reward_d_coef: 2.0
  discriminator_lr: ${discriminator_lr}
  spectral_norm_bool: ${spectral_norm_bool}
  GAN_loss: ${GAN_loss}
  stochastic_encoder: ${stochastic_encoder}
  from_dem: ${from_dem}
  check_every_steps: ${check_every_steps}
  from_depth: ${from_depth}
  midas_size: ${midas_size}
  add_aug: ${add_aug}
  depth_flag: ${depth_flag}
  segm_flag: ${segm_flag}

