defaults:
  - _self_
  - replay_buffer@_global_: numpy
  - replay_buffer_expert@_global_: numpy
  - task@_global_: walker_walk
  - agent@_global_: disentAIL
  - expert@_global_: ddpg
  - difficulty@_global_: no_mismatch
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 3
action_repeat: 1
discount: 0.99
image_height: 64
image_width: 64
# train settings
num_seed_frames: 4000
num_expl_frames: 10000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
save_replay_buffers: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: false
save_train_video: false
use_tb: false

# experiment
experiment: exp
# agent
lr: 1e-4
lr_BYOL: 1e-4
feature_dim: 50
stochastic_encoder: false
stochastic_preprocessor: true
# expert data
num_expert_episodes: 100
frame_skip: 1
expert_replay_buffer_size: 100000
#discriminator feat
discriminator_lr: 1e-4
spectral_norm_bool: false
GAN_loss: bce
from_dem: false

# MI
dual_mi_constant: 1.0
dual_max_mi: 0.001
dual_min_mi_constant: 1e-3
max_mi: 0.99
min_mi: 0.495
min_mi_constant: 1e-4
max_mi_constant: 5.0
mi_constant: 0.5
unbiased_mi_decay: 0.99

# other
check_every_steps: 5000
depth_flag: false # Enables learning from perfect depth
segm_flag: false # Enables learning from perfect segmentation
add_aug: false # adds additional augmentations to BYOL and CL agents
brightness_only: true # augmentation focuses mainly on brigthness
deeper_head: false # in the projected setting it makes the encoder head deeper

# multi-dataset
train_encoder_w_critic: true
CL_data_type: all

# multi envs
num_aug_envs: 10
aug: true

hydra:
  run:
    dir: ./experiments/exp_delta_source=${delta_source}_delta_target=${delta_target}/${agent_name}_add_aug=${add_aug}_train_encoder_w_critic=${train_encoder_w_critic}_CL_data_type=${CL_data_type}_${now:%Y.%m.%d}/${now:%H%M}_${hydra.job.override_dirname}
  sweep:
    dir: ./experiments/exp_multirun_delta_source=${delta_source}_delta_target=${delta_target}/${agent_name}_add_aug=${add_aug}_train_encoder_w_critic=${train_encoder_w_critic}_CL_data_type=${CL_data_type}/
    subdir: ${now:%Y.%m.%d}_${now:%H%M}_${hydra.job.override_dirname}
  launcher:
    timeout_min: 18000000
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./experiments/exp_multirun_delta_source=${delta_source}_delta_target=${delta_target}/${agent_name}_add_aug=${add_aug}_train_encoder_w_critic=${train_encoder_w_critic}_CL_data_type=${CL_data_type}/
