defaults:
  - _self_
  - replay_buffer@_global_: numpy_depth
  - replay_buffer_expert@_global_: numpy_depth
  - task@_global_: walker_walk
  - agent@_global_: lail
  - expert@_global_: ddpg
  - difficulty@_global_: no_mismatch
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 3
action_repeat: 1
discount: 0.99
image_height: 64
image_width: 64
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: false
save_train_video: false
use_tb: false

# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 50
# expert data
num_expert_episodes: 100
frame_skip: 1
#discriminator feat
discriminator_lr: 4e-4
spectral_norm_bool: false
GAN_loss: bce
from_dem: false

# DA
from_depth: true
midas_size: small
add_aug: false

# other
check_every_steps: 5000
depth_flag: false
segm_flag: false

#bisim
transition_model_type: deterministic

hydra:
  run:
    dir: ./experiments/exp_difficulty_${difficulty}_depth_${depth_flag}_segm_${segm_flag}/${agent_name}_add_aug_${add_false}_${now:%Y.%m.%d}/${now:%H%M}_${hydra.job.override_dirname}
  sweep:
    dir: ./experiments/exp_multirun_${difficulty}_depth_${depth_flag}_segm_${segm_flag}_${task_name}_num_expert_episodes_${num_expert_episodes}/${agent_name}_add_aug_${add_false}_from_depth_${from_depth}/
    subdir: ${now:%Y.%m.%d}_${now:%H%M}_${hydra.job.override_dirname}
  launcher:
    timeout_min: 18000000
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./experiments/exp_multirun_${difficulty}_depth_${depth_flag}_segm_${segm_flag}_${task_name}_num_expert_episodes_${num_expert_episodes}/${agent_name}_add_aug_${add_false}_from_depth_${from_depth}/
